package com.rocybyte.weisome.ui

import androidx.compose.ui.graphics.Color

/** Color tokens of the Vivid Precision light scheme defined in DESIGN.md. */
internal object WeiSomeColors {
    val surface = Color(0xFFF9F9F9)
    val surfaceDim = Color(0xFFDADADA)
    val surfaceBright = Color(0xFFF9F9F9)
    val surfaceContainerLowest = Color(0xFFFFFFFF)
    val surfaceContainerLow = Color(0xFFF3F3F4)
    val surfaceContainer = Color(0xFFEEEEEE)
    val surfaceContainerHigh = Color(0xFFE8E8E8)
    val surfaceContainerHighest = Color(0xFFE2E2E2)
    val onSurface = Color(0xFF1A1C1C)
    val onSurfaceVariant = Color(0xFF414755)
    val inverseSurface = Color(0xFF2F3131)
    val inverseOnSurface = Color(0xFFF0F1F1)
    val outline = Color(0xFF717786)
    val outlineVariant = Color(0xFFC1C6D7)
    val surfaceTint = Color(0xFF005BC1)
    val primary = Color(0xFF0058BC)
    val onPrimary = Color(0xFFFFFFFF)
    val primaryContainer = Color(0xFF0070EB)
    val onPrimaryContainer = Color(0xFFFEFCFF)
    val inversePrimary = Color(0xFFADC6FF)
    val secondary = Color(0xFFB42907)
    val onSecondary = Color(0xFFFFFFFF)
    val secondaryContainer = Color(0xFFFE5D39)
    val onSecondaryContainer = Color(0xFF5B0D00)
    val tertiary = Color(0xFF8D22C0)
    val onTertiary = Color(0xFFFFFFFF)
    val tertiaryContainer = Color(0xFFA943DC)
    val onTertiaryContainer = Color(0xFFFFFBFF)
    val error = Color(0xFFBA1A1A)
    val onError = Color(0xFFFFFFFF)
    val errorContainer = Color(0xFFFFDAD6)
    val onErrorContainer = Color(0xFF93000A)
    val primaryFixed = Color(0xFFD8E2FF)
    val primaryFixedDim = Color(0xFFADC6FF)
    val onPrimaryFixed = Color(0xFF001A41)
    val onPrimaryFixedVariant = Color(0xFF004493)
    val secondaryFixed = Color(0xFFFFDAD2)
    val secondaryFixedDim = Color(0xFFFFB4A3)
    val onSecondaryFixed = Color(0xFF3D0600)
    val onSecondaryFixedVariant = Color(0xFF8B1A00)
    val tertiaryFixed = Color(0xFFF6D9FF)
    val tertiaryFixedDim = Color(0xFFE9B3FF)
    val onTertiaryFixed = Color(0xFF310048)
    val onTertiaryFixedVariant = Color(0xFF7200A3)
    val background = Color(0xFFF9F9F9)
    val onBackground = Color(0xFF1A1C1C)
    val surfaceVariant = Color(0xFFE2E2E2)

    /** Card edge color from the DESIGN.md component specs. */
    val cardBorder = Color(0xFFF2F2F7)
}
