package com.rocybyte.weisome.page.article.widget

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.rocybyte.weisome.article.CodeTheme
import com.rocybyte.weisome.article.MarkdownThemeId

/** Typography and decoration spec for one heading level. */
internal data class HeadingSpec(
    val size: Float,
    val weight: FontWeight,
    val top: Int,
    val bottom: Int,
    val borderLeft: Boolean,
    val borderWidth: Dp,
    val borderBottom: Boolean,
    val muted: Boolean,
    val lineHeightMultiplier: Float,
)

/**
 * Compose preview styles for one Markdown document theme.
 * HYDROGEN mirrors docs/theme/hydrogen/hydrogen.scss (DawnLck/juejin-markdown-theme-hydrogen@b3f86fb),
 * GITHUB mirrors docs/theme/github/github.scss (primer/css src/markdown, light values resolved),
 * SMART_BLUE mirrors docs/theme/smart-blue/smart-blue.css (cumt-robin/juejin-markdown-theme-smart-blue@f740565).
 * TYPORA_PAPER mirrors docs/theme/typora-paper at lisitan/esther-obsidian-typora-themes@8c4f912.
 * RIM mirrors docs/theme/rim/rim.css at Rimseg/typora-theme-rim@f0d54ef.
 * Keep the data module HTML export (MarkdownExportStyles) aligned with these values.
 */
internal data class MarkdownPreviewStyles(
    val bodyColor: Color,
    val mutedColor: Color,
    val headingColor: Color,
    val themeColor: Color,
    val linkColor: Color,
    val boldColor: Color?,
    val linkUnderlined: Boolean,
    val linkHasIcon: Boolean,
    val firstLetterCapitalized: Boolean,
    val h1HasPrefix: Boolean,
    val h1Centered: Boolean,
    val headingBorderColor: Color,
    val headingBottomBorderColor: Color,
    val bodyFontSize: androidx.compose.ui.unit.TextUnit,
    val bodyLineHeight: androidx.compose.ui.unit.TextUnit,
    val paragraphTopMargin: Int,
    val paragraphBottomMargin: Int,
    val quoteParagraphTopMargin: Int,
    val quoteParagraphBottomMargin: Int,
    val quoteColor: Color,
    val quoteBackground: Color,
    val quoteBorder: Color,
    val quoteHasBackground: Boolean,
    val quoteHasMarks: Boolean,
    val quoteHasHover: Boolean,
    val quotePaddingStart: Int,
    val quotePaddingEnd: Int,
    val quotePaddingTop: Int,
    val quotePaddingBottom: Int,
    val quoteVerticalMargin: Int,
    val quoteNestedVerticalMargin: Int,
    val inlineCodeColor: Color,
    val inlineCodeBackground: Color,
    val inlineCodeFontScale: Float,
    val inlineCodeCornerRadius: Dp,
    val codeBlockTopMargin: Int,
    val codeBlockBottomMargin: Int,
    val codeBlockCornerShape: androidx.compose.foundation.shape.RoundedCornerShape,
    val codeBlockPaddingVertical: Int,
    val codeBlockPaddingHorizontal: Int,
    val codeBlockFontSize: androidx.compose.ui.unit.TextUnit,
    val codeBlockLineHeight: androidx.compose.ui.unit.TextUnit,
    val strikethroughColor: Color,
    val tableBorderColor: Color,
    val tableBorderWidth: Dp,
    val tableHeaderBackground: Color,
    val tableHeaderColor: Color,
    val tableHeaderFontWeight: FontWeight,
    val tableStripeBackground: Color,
    val tableCellPaddingHorizontal: Int,
    val tableCellPaddingVertical: Int,
    val tableFontSize: androidx.compose.ui.unit.TextUnit,
    val tableLineHeight: androidx.compose.ui.unit.TextUnit,
    val ruleIsGradient: Boolean,
    val ruleGradient: List<Color>,
    val ruleSolidColor: Color,
    val ruleHeight: Dp,
    val ruleVerticalMargin: Int,
    val listPaddingStart: Int,
    val listTopMargin: Int,
    val listBottomMargin: Int,
    val listItemTopMargin: Int,
    val orderedItemExtraPaddingStart: Int,
    val nestedListPaddingStart: Int,
    val nestedListTopMargin: Int,
    private val headingSpecs: List<HeadingSpec>,
    val h1AccentBar: Boolean = false,
    val h2AccentDots: Boolean = false,
    val quoteBorderWidth: Dp = 4.dp,
    val quoteCornerRadius: Dp = 0.dp,
    val quoteShadowElevation: Dp = 0.dp,
    val quoteMarkColor: Color = Color.Unspecified,
    val quoteMarkFontSize: androidx.compose.ui.unit.TextUnit = 24.sp,
    val quoteHasClosingMark: Boolean = true,
    val codeBlockHasWindowHeader: Boolean = false,
    val codeBlockFrameColor: Color = Color.Transparent,
    val codeBlockBorderColor: Color = Color.Transparent,
    val codeBlockBorderWidth: Dp = 0.dp,
    val codeBlockShadowElevation: Dp = 0.dp,
    val ruleWidthFraction: Float = 1f,
    val ruleHasPaperAccents: Boolean = false,
    val unorderedMarkerColor: Color = Color.Unspecified,
    val orderedMarkerColor: Color = Color.Unspecified,
    val imageCornerRadius: Dp = 2.dp,
    val imageShadowElevation: Dp = 0.dp,
    val tableCornerRadius: Dp = 0.dp,
    val tableShadowElevation: Dp = 0.dp,
) {
    /** Returns the heading spec for a level from 1 to 6. */
    fun headingSpec(level: Int): HeadingSpec = headingSpecs[(level - 1).coerceIn(0, headingSpecs.lastIndex)]

    /** Returns the configured font size for a heading level. */
    fun headingFontSize(level: Int) = headingSpec(level).size.sp

    /** Returns the configured font weight for a heading level. */
    fun headingFontWeight(level: Int) = headingSpec(level).weight

    /** Returns the configured top margin for a heading level. */
    fun headingTopMargin(level: Int) = headingSpec(level).top.dp

    /** Returns the configured bottom margin for a heading level. */
    fun headingBottomMargin(level: Int) = headingSpec(level).bottom.dp
}

/** Returns the preview style set for the requested Markdown theme. */
internal fun previewStylesFor(theme: MarkdownThemeId): MarkdownPreviewStyles = when (theme) {
    MarkdownThemeId.GITHUB -> GitHubPreviewStyles
    MarkdownThemeId.HYDROGEN -> HydrogenPreviewStyles
    MarkdownThemeId.SMART_BLUE -> SmartBluePreviewStyles
    MarkdownThemeId.TYPORA_PAPER -> TyporaPaperPreviewStyles
    MarkdownThemeId.RIM -> RimPreviewStyles
}

/** Provides the active Markdown preview styles to the block widgets. */
internal val LocalMarkdownPreviewStyles = staticCompositionLocalOf<MarkdownPreviewStyles> {
    error("MarkdownPreviewStyles is not provided")
}

/** Provides the active code theme palette to the code block widget. */
internal val LocalCodeTheme = staticCompositionLocalOf<CodeTheme> {
    error("CodeTheme is not provided")
}

/** Hydrogen preview styles; values mirror docs/theme/hydrogen/hydrogen.scss. */
internal val HydrogenPreviewStyles = MarkdownPreviewStyles(
    bodyColor = Color(0xDE2E2424),
    mutedColor = Color(0xFF59636E),
    headingColor = Color(0xDE2E2424),
    themeColor = Color(0xFF1976D2),
    linkColor = Color(0xFF027FFF),
    boldColor = null,
    linkUnderlined = false,
    linkHasIcon = true,
    firstLetterCapitalized = true,
    h1HasPrefix = true,
    h1Centered = false,
    headingBorderColor = Color(0xFF454545),
    headingBottomBorderColor = Color(0xFFD1D9E0),
    bodyFontSize = 16.sp,
    bodyLineHeight = 28.sp,
    paragraphTopMargin = 22,
    paragraphBottomMargin = 22,
    quoteParagraphTopMargin = 10,
    quoteParagraphBottomMargin = 10,
    quoteColor = Color(0xFF666666),
    quoteBackground = Color(0x1FC8C8C8),
    quoteBorder = Color(0xFFCBCBCB),
    quoteHasBackground = true,
    quoteHasMarks = true,
    quoteHasHover = true,
    quotePaddingStart = 27,
    quotePaddingEnd = 23,
    quotePaddingTop = 5,
    quotePaddingBottom = 1,
    quoteVerticalMargin = 22,
    quoteNestedVerticalMargin = 10,
    inlineCodeColor = Color(0xFFC0341D),
    inlineCodeBackground = Color(0xFFFBE5E1),
    inlineCodeFontScale = 0.87f,
    inlineCodeCornerRadius = 2.dp,
    codeBlockTopMargin = 22,
    codeBlockBottomMargin = 22,
    codeBlockCornerShape = androidx.compose.foundation.shape.RoundedCornerShape(0.dp, 4.dp, 0.dp, 4.dp),
    codeBlockPaddingVertical = 15,
    codeBlockPaddingHorizontal = 12,
    codeBlockFontSize = 12.sp,
    codeBlockLineHeight = 21.sp,
    strikethroughColor = Color(0x99000000),
    tableBorderColor = Color(0xFFC6C6C6),
    tableBorderWidth = 2.dp,
    tableHeaderBackground = Color(0xFFF6F6F6),
    tableHeaderColor = Color.Black,
    tableHeaderFontWeight = FontWeight.Normal,
    tableStripeBackground = Color(0xFFFCFCFC),
    tableCellPaddingHorizontal = 7,
    tableCellPaddingVertical = 12,
    tableFontSize = 12.sp,
    tableLineHeight = 24.sp,
    ruleIsGradient = true,
    ruleGradient = listOf(Color(0xFFDDDDDD), Color(0xFF999999), Color(0xFFDDDDDD)),
    ruleSolidColor = Color(0xFFD1D9E0),
    ruleHeight = 1.dp,
    ruleVerticalMargin = 32,
    listPaddingStart = 28,
    listTopMargin = 16,
    listBottomMargin = 16,
    listItemTopMargin = 0,
    orderedItemExtraPaddingStart = 6,
    nestedListPaddingStart = 28,
    nestedListTopMargin = 3,
    headingSpecs = listOf(
        HeadingSpec(30f, FontWeight.Medium, 35, 5, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
        // The 15px bottom is hydrogen's 10px h2 margin plus its 5px shared padding-bottom.
        HeadingSpec(28f, FontWeight.Normal, 20, 15, borderLeft = true, borderWidth = 5.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
        HeadingSpec(24f, FontWeight.Normal, 15, 10, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
        HeadingSpec(20f, FontWeight.Medium, 35, 10, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
        HeadingSpec(16f, FontWeight.Normal, 35, 10, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
        // hydrogen defines no h6 font-size; the body base of 16px is used instead.
        HeadingSpec(16f, FontWeight.Normal, 5, 10, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
    ),
)

/** GitHub preview styles; values mirror docs/theme/github/github.scss (primer/css markdown, light). */
internal val GitHubPreviewStyles = MarkdownPreviewStyles(
    bodyColor = Color(0xFF1F2328),
    mutedColor = Color(0xFF59636E),
    headingColor = Color(0xFF1F2328),
    themeColor = Color(0xFF0969DA),
    linkColor = Color(0xFF0969DA),
    boldColor = null,
    linkUnderlined = true,
    linkHasIcon = false,
    firstLetterCapitalized = false,
    h1HasPrefix = false,
    h1Centered = false,
    headingBorderColor = Color(0xFF454545),
    headingBottomBorderColor = Color(0xFFD1D9E0),
    bodyFontSize = 16.sp,
    bodyLineHeight = 24.sp,
    paragraphTopMargin = 0,
    paragraphBottomMargin = 16,
    quoteParagraphTopMargin = 0,
    quoteParagraphBottomMargin = 16,
    quoteColor = Color(0xFF59636E),
    // Only used as the inline-image placeholder fill; blockquotes render without a background.
    quoteBackground = Color(0x33AFB9C9),
    quoteBorder = Color(0xFFD1D9E0),
    quoteHasBackground = false,
    quoteHasMarks = false,
    quoteHasHover = false,
    quotePaddingStart = 16,
    quotePaddingEnd = 16,
    quotePaddingTop = 0,
    quotePaddingBottom = 0,
    quoteVerticalMargin = 16,
    quoteNestedVerticalMargin = 16,
    inlineCodeColor = Color(0xFF1F2328),
    inlineCodeBackground = Color(0x33AFB9C9),
    inlineCodeFontScale = 0.85f,
    inlineCodeCornerRadius = 6.dp,
    codeBlockTopMargin = 0,
    codeBlockBottomMargin = 16,
    codeBlockCornerShape = androidx.compose.foundation.shape.RoundedCornerShape(6.dp),
    codeBlockPaddingVertical = 16,
    codeBlockPaddingHorizontal = 16,
    codeBlockFontSize = 13.6.sp,
    codeBlockLineHeight = 19.72.sp,
    strikethroughColor = Color(0xFF1F2328),
    tableBorderColor = Color(0xFFD1D9E0),
    tableBorderWidth = 1.dp,
    tableHeaderBackground = Color.Transparent,
    tableHeaderColor = Color(0xFF1F2328),
    tableHeaderFontWeight = FontWeight.SemiBold,
    tableStripeBackground = Color(0xFFF6F8FA),
    tableCellPaddingHorizontal = 13,
    tableCellPaddingVertical = 6,
    tableFontSize = 16.sp,
    tableLineHeight = 24.sp,
    ruleIsGradient = false,
    ruleGradient = emptyList(),
    ruleSolidColor = Color(0xFFD1D9E0),
    ruleHeight = 4.dp,
    ruleVerticalMargin = 24,
    listPaddingStart = 32,
    listTopMargin = 0,
    listBottomMargin = 16,
    listItemTopMargin = 4,
    orderedItemExtraPaddingStart = 0,
    nestedListPaddingStart = 32,
    nestedListTopMargin = 0,
    headingSpecs = listOf(
        HeadingSpec(32f, FontWeight.SemiBold, 24, 16, borderLeft = false, borderWidth = 0.dp, borderBottom = true, muted = false, lineHeightMultiplier = 1.25f),
        HeadingSpec(24f, FontWeight.SemiBold, 24, 16, borderLeft = false, borderWidth = 0.dp, borderBottom = true, muted = false, lineHeightMultiplier = 1.25f),
        HeadingSpec(20f, FontWeight.SemiBold, 24, 16, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.25f),
        HeadingSpec(16f, FontWeight.SemiBold, 24, 16, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.25f),
        HeadingSpec(14f, FontWeight.SemiBold, 24, 16, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.25f),
        HeadingSpec(13.6f, FontWeight.SemiBold, 24, 16, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = true, lineHeightMultiplier = 1.25f),
    ),
)

/**
 * smart-blue preview styles; values mirror docs/theme/smart-blue/smart-blue.css.
 * The h1 juejin-logo watermark is absent from the reference stylesheet, and the `.markdown-body`
 * grid background and `kbd` rule are intentionally not rendered. Paragraph spacing approximates
 * `p + p { margin-top: 16px }` with a top margin (the model has no sibling selector), and quote
 * paragraphs keep the stylesheet's tight 2px inset because `blockquote p` defines no margin.
 */
internal val SmartBluePreviewStyles = MarkdownPreviewStyles(
    bodyColor = Color(0xFF595959),
    // Unused: no smart-blue heading takes the muted color.
    mutedColor = Color(0xFF666666),
    headingColor = Color(0xFF135CE0),
    themeColor = Color(0xFF135CE0),
    linkColor = Color(0xFF036ACA),
    boldColor = Color(0xFF036ACA),
    linkUnderlined = true,
    linkHasIcon = false,
    firstLetterCapitalized = false,
    h1HasPrefix = false,
    h1Centered = true,
    headingBorderColor = Color(0xFF135CE0),
    // Unused: no smart-blue heading renders a bottom border.
    headingBottomBorderColor = Color(0xFFDFE2E5),
    bodyFontSize = 15.sp,
    bodyLineHeight = 30.sp,
    paragraphTopMargin = 16,
    paragraphBottomMargin = 0,
    quoteParagraphTopMargin = 0,
    quoteParagraphBottomMargin = 0,
    quoteColor = Color(0xFF666666),
    quoteBackground = Color(0xFFFFF9F9),
    quoteBorder = Color(0xFFB2AEC5),
    quoteHasBackground = true,
    quoteHasMarks = false,
    quoteHasHover = false,
    // 24 = the stylesheet's 20px padding-left plus the 4px left border the widget paints inside.
    quotePaddingStart = 24,
    quotePaddingEnd = 20,
    quotePaddingTop = 2,
    quotePaddingBottom = 2,
    quoteVerticalMargin = 30,
    quoteNestedVerticalMargin = 30,
    inlineCodeColor = Color(0xFFFF502C),
    inlineCodeBackground = Color(0xFFFFF5F5),
    inlineCodeFontScale = 0.87f,
    inlineCodeCornerRadius = 2.dp,
    codeBlockTopMargin = 15,
    codeBlockBottomMargin = 15,
    codeBlockCornerShape = androidx.compose.foundation.shape.RoundedCornerShape(0.dp),
    codeBlockPaddingVertical = 15,
    codeBlockPaddingHorizontal = 12,
    codeBlockFontSize = 12.sp,
    codeBlockLineHeight = 21.sp,
    strikethroughColor = Color(0xFF595959),
    tableBorderColor = Color(0xFFDFE2E5),
    tableBorderWidth = 1.dp,
    tableHeaderBackground = Color.Transparent,
    tableHeaderColor = Color(0xFF595959),
    tableHeaderFontWeight = FontWeight.Bold,
    tableStripeBackground = Color(0xFFF6F8FA),
    tableCellPaddingHorizontal = 15,
    tableCellPaddingVertical = 9,
    tableFontSize = 15.sp,
    // The stylesheet sets no cell line-height, i.e. the browser's normal (about 1.2 x 15px).
    tableLineHeight = 18.sp,
    ruleIsGradient = false,
    ruleGradient = emptyList(),
    ruleSolidColor = Color(0xFF135CE0),
    ruleHeight = 1.dp,
    // The stylesheet sets only the top border; 8px is its .5em browser default at the 15px body size.
    ruleVerticalMargin = 8,
    // 70 = the stylesheet's 2em ul margin-left plus the browser's 40px padding-left; ordered lists
    // share it because the model carries a single list indent.
    listPaddingStart = 70,
    listTopMargin = 15,
    listBottomMargin = 15,
    listItemTopMargin = 0,
    orderedItemExtraPaddingStart = 0,
    nestedListPaddingStart = 70,
    nestedListTopMargin = 15,
    headingSpecs = listOf(
        // The stylesheet's symmetric 80px (50 margin + 30 padding) becomes hydrogen's asymmetric h1
        // rhythm, which renders 35px above and 27px below. The 10px here plus the paragraph's 16px
        // top margin render 26px, the same gap the export writes as the heading's own bottom margin.
        HeadingSpec(22f, FontWeight.Bold, 35, 10, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
        HeadingSpec(20f, FontWeight.Bold, 30, 30, borderLeft = true, borderWidth = 4.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
        HeadingSpec(16f, FontWeight.Bold, 30, 30, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
        // h4 to h6 keep the shared rule and fall back to the browser's 1em/0.83em/0.67em at 15px.
        HeadingSpec(15f, FontWeight.Bold, 30, 30, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
        HeadingSpec(12.45f, FontWeight.Bold, 30, 30, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
        HeadingSpec(10.05f, FontWeight.Bold, 30, 30, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.5f),
    ),
)

/** Typora Paper preview styles adapted from Esther Inspired Paper at commit 8c4f912. */
internal val TyporaPaperPreviewStyles = MarkdownPreviewStyles(
    bodyColor = Color(0xFF1A1A2E),
    mutedColor = Color(0xFF555568),
    headingColor = Color(0xFF17172A),
    themeColor = Color(0xFF2B7FD8),
    linkColor = Color(0xFF2B7FD8),
    boldColor = Color(0xFF17172A),
    linkUnderlined = true,
    linkHasIcon = false,
    firstLetterCapitalized = false,
    h1HasPrefix = false,
    h1Centered = false,
    headingBorderColor = Color.Transparent,
    headingBottomBorderColor = Color(0xFFE8E0CF),
    bodyFontSize = 16.sp,
    bodyLineHeight = 29.12.sp,
    paragraphTopMargin = 16,
    paragraphBottomMargin = 16,
    quoteParagraphTopMargin = 0,
    quoteParagraphBottomMargin = 0,
    quoteColor = Color(0xFF555568),
    quoteBackground = Color.White,
    quoteBorder = Color.Transparent,
    quoteHasBackground = true,
    quoteHasMarks = true,
    quoteHasHover = false,
    quotePaddingStart = 59,
    quotePaddingEnd = 28,
    quotePaddingTop = 25,
    quotePaddingBottom = 23,
    quoteVerticalMargin = 27,
    quoteNestedVerticalMargin = 16,
    inlineCodeColor = Color(0xFFB43C50),
    inlineCodeBackground = Color(0xFFF5EFE1),
    inlineCodeFontScale = 0.88f,
    inlineCodeCornerRadius = 6.dp,
    codeBlockTopMargin = 24,
    codeBlockBottomMargin = 24,
    codeBlockCornerShape = androidx.compose.foundation.shape.RoundedCornerShape(15.dp),
    codeBlockPaddingVertical = 20,
    codeBlockPaddingHorizontal = 19,
    codeBlockFontSize = 14.08.sp,
    codeBlockLineHeight = 23.65.sp,
    strikethroughColor = Color(0xFF1A1A2E),
    tableBorderColor = Color(0xFFE8E0CF),
    tableBorderWidth = 1.dp,
    tableHeaderBackground = Color(0x1A2B7FD8),
    tableHeaderColor = Color(0xFF17172A),
    tableHeaderFontWeight = FontWeight.ExtraBold,
    tableStripeBackground = Color(0xFFFAF6EB),
    tableCellPaddingHorizontal = 14,
    tableCellPaddingVertical = 12,
    tableFontSize = 16.sp,
    tableLineHeight = 29.12.sp,
    ruleIsGradient = false,
    ruleGradient = emptyList(),
    ruleSolidColor = Color(0xFFF4D758),
    ruleHeight = 5.dp,
    ruleVerticalMargin = 51,
    listPaddingStart = 26,
    listTopMargin = 16,
    listBottomMargin = 16,
    listItemTopMargin = 5,
    orderedItemExtraPaddingStart = 3,
    nestedListPaddingStart = 26,
    nestedListTopMargin = 3,
    headingSpecs = listOf(
        HeadingSpec(50.4f, FontWeight.ExtraBold, 28, 36, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.18f),
        HeadingSpec(32f, FontWeight.ExtraBold, 67, 23, borderLeft = false, borderWidth = 0.dp, borderBottom = true, muted = false, lineHeightMultiplier = 1.35f),
        HeadingSpec(21.6f, FontWeight.ExtraBold, 45, 16, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.35f),
        HeadingSpec(17.92f, FontWeight.ExtraBold, 38, 13, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.35f),
        HeadingSpec(15.68f, FontWeight.ExtraBold, 33, 11, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.35f),
        HeadingSpec(14.08f, FontWeight.ExtraBold, 30, 10, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = true, lineHeightMultiplier = 1.35f),
    ),
    h1AccentBar = true,
    h2AccentDots = true,
    quoteBorderWidth = 0.dp,
    quoteCornerRadius = 18.dp,
    quoteShadowElevation = 10.dp,
    quoteMarkColor = Color(0xFFF4D758),
    quoteMarkFontSize = 73.6.sp,
    quoteHasClosingMark = false,
    codeBlockHasWindowHeader = true,
    codeBlockFrameColor = Color(0xFFEEF0F4),
    codeBlockBorderColor = Color(0xFFD9DDE5),
    codeBlockBorderWidth = 1.dp,
    codeBlockShadowElevation = 12.dp,
    ruleWidthFraction = 0.42f,
    ruleHasPaperAccents = true,
    unorderedMarkerColor = Color(0xFFE84A5F),
    orderedMarkerColor = Color(0xFF2B7FD8),
    imageCornerRadius = 14.dp,
    imageShadowElevation = 12.dp,
    tableCornerRadius = 14.dp,
    tableShadowElevation = 6.dp,
)

/** Rim preview styles adapted from typora-theme-rim at commit f0d54ef. */
internal val RimPreviewStyles = MarkdownPreviewStyles(
    bodyColor = Color(0xFF13202C),
    mutedColor = Color(0xFF47525D),
    headingColor = Color(0xFF152E45),
    themeColor = Color(0xFF4E3E8B),
    linkColor = Color(0xFF3E3282),
    boldColor = null,
    linkUnderlined = true,
    linkHasIcon = false,
    firstLetterCapitalized = false,
    h1HasPrefix = false,
    h1Centered = false,
    headingBorderColor = Color.Transparent,
    headingBottomBorderColor = Color.Transparent,
    bodyFontSize = 18.sp,
    bodyLineHeight = 30.6.sp,
    paragraphTopMargin = 14,
    paragraphBottomMargin = 14,
    quoteParagraphTopMargin = 14,
    quoteParagraphBottomMargin = 14,
    quoteColor = Color(0xFF13202C),
    quoteBackground = Color.Transparent,
    quoteBorder = Color(0xFF4E3E8B),
    quoteHasBackground = false,
    quoteHasMarks = false,
    quoteHasHover = false,
    quotePaddingStart = 17,
    quotePaddingEnd = 15,
    quotePaddingTop = 0,
    quotePaddingBottom = 0,
    quoteVerticalMargin = 14,
    quoteNestedVerticalMargin = 14,
    inlineCodeColor = Color(0xFF00711E),
    inlineCodeBackground = Color(0xFFF8F6F6),
    inlineCodeFontScale = 0.8f,
    inlineCodeCornerRadius = 3.dp,
    codeBlockTopMargin = 15,
    codeBlockBottomMargin = 15,
    codeBlockCornerShape = androidx.compose.foundation.shape.RoundedCornerShape(3.dp),
    codeBlockPaddingVertical = 7,
    codeBlockPaddingHorizontal = 8,
    codeBlockFontSize = 14.4.sp,
    codeBlockLineHeight = 20.16.sp,
    strikethroughColor = Color(0xFF13202C),
    tableBorderColor = Color(0xFFCCCCCC),
    tableBorderWidth = 1.dp,
    tableHeaderBackground = Color.Transparent,
    tableHeaderColor = Color(0xFF13202C),
    tableHeaderFontWeight = FontWeight.Bold,
    tableStripeBackground = Color.Transparent,
    tableCellPaddingHorizontal = 0,
    tableCellPaddingVertical = 6,
    tableFontSize = 14.4.sp,
    tableLineHeight = 20.16.sp,
    ruleIsGradient = false,
    ruleGradient = emptyList(),
    ruleSolidColor = Color(0xFFDEDEDE),
    ruleHeight = 2.dp,
    ruleVerticalMargin = 16,
    listPaddingStart = 20,
    listTopMargin = 14,
    listBottomMargin = 14,
    listItemTopMargin = 0,
    orderedItemExtraPaddingStart = 0,
    nestedListPaddingStart = 20,
    nestedListTopMargin = 0,
    headingSpecs = listOf(
        HeadingSpec(34.2f, FontWeight.Bold, 18, 18, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.3f),
        HeadingSpec(28.8f, FontWeight.Bold, 43, 18, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.3f),
        HeadingSpec(23.4f, FontWeight.SemiBold, 36, 18, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.3f),
        HeadingSpec(20.7f, FontWeight.SemiBold, 32, 18, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.3f),
        HeadingSpec(18f, FontWeight.SemiBold, 29, 18, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = false, lineHeightMultiplier = 1.3f),
        HeadingSpec(18f, FontWeight.SemiBold, 29, 18, borderLeft = false, borderWidth = 0.dp, borderBottom = false, muted = true, lineHeightMultiplier = 1.3f),
    ),
    quoteBorderWidth = 3.dp,
    codeBlockBorderColor = Color(0xFFE7EAED),
    codeBlockBorderWidth = 1.dp,
)

/** Converts a packed RGB value to an opaque Compose color. */
internal fun Int.toComposeColor(): Color = Color(0xFF000000L or (toLong() and 0xFFFFFFL))
